shared:
  image: node:12
 
jobs:
  validate:
    requires: [~pr, ~commit]
    steps:
      - validate: sd-cmd validate -f ./sd-command.yaml
 
  publish:
    requires: [validate]
    steps:
      - publish: sd-cmd publish -f ./sd-command.yaml
  
  promote:
    requires: [publish]
    steps:
      - sd-cmd promote sugarnaoming/sum latest stable
      
  use-cmd:
    requires: []
    steps:  
      - sd-cmd exec sugarnaoming/sum@1.0.0 1 1
   
  token:
     requires: []
     steps:
       - echo ${SD_TOKEN}
